stages:
  - test
  - benchmark-build
  - benchmark-run


variables:
  GIT_SUBMODULE_STRATEGY: recursive


test:
  stage: test
  tags:
    - docker
  image: buildpack-deps:bionic
  script:
    - make test


benchmark-build:pc189:
  stage: benchmark-build
  tags:
    - pc189
  only:
    - master
  when: manual
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - source ~/pdmkp_env
    - make
  artifacts:
    paths:
      - traffic_sim
      - build

benchmark-build:pc205:
  stage: benchmark-build
  tags:
    - pc205
  only:
    - master
  when: manual
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - source ~/pdmkp_env
    - make
  artifacts:
    paths:
      - traffic_sim
      - build


benchmark-run:pc189:
  stage: benchmark-run
  tags:
    - pc189
  only:
    - master
  when: manual
  dependencies:
    - benchmark-build:pc189
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - source ~/pdmkp_env
    - traffic_check $PWD/traffic_sim

benchmark-run:pc205:
  stage: benchmark-run
  tags:
    - pc205
  only:
    - master
  when: manual
  dependencies:
    - benchmark-build:pc205
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - source ~/pdmkp_env
    - traffic_check $PWD/traffic_sim
