stages:
  - build
  - test

build:pc189:
  stage: build
  tags:
    - pc189
  only:
    - master
  when: manual
  artifacts:
    paths:
      - traffic_sim
      - build
  script:
    - source ~/pdmkp_env
    - make

build:pc205:
  stage: build
  tags:
    - pc205
  only:
    - master
  when: manual
  artifacts:
    paths:
      - traffic_sim
      - build
  script:
    - source ~/pdmkp_env
    - make


test:pc189:
  stage: test
  tags:
    - pc189
  only:
    - master
  when: manual
  dependencies:
    - build:pc189
  script:
    - source ~/pdmkp_env
    - traffic_check $PWD/traffic_sim

test:pc205:
  stage: test
  tags:
    - pc205
  only:
    - master
  when: manual
  dependencies:
    - build:pc205
  script:
    - source ~/pdmkp_env
    - traffic_check $PWD/traffic_sim
