stages:
  - test
  - benchmark


variables:
  GIT_SUBMODULE_STRATEGY: recursive


test:
  stage: test
  tags:
    - docker
  image: buildpack-deps:bionic
  script:
    - make test

test-omp:
  stage: test
  tags:
    - docker
  image: buildpack-deps:bionic
  variables:
    OMP: "1"
  script:
    - make test


benchmark:pc189:
  stage: benchmark
  tags:
    - pc189
  when: manual
  variables:
    OMP: "1"
    GIT_SUBMODULE_STRATEGY: none
  script:
    - source ~/pdmkp_env
    - make
    - traffic_check $PWD/traffic_sim

benchmark:pc205:
  stage: benchmark
  tags:
    - pc205
  when: manual
  variables:
    OMP: "1"
  script:
    - source ~/pdmkp_env
    - make
    - traffic_check $PWD/traffic_sim
